export const maps = [
  [
    'bbbbbbababababbbbbbffbbabbbbaaaaaaaaaaagababbabbbabababbabafabbababbbbbbbbfgaaaaaababbaabbabababbabgf',
    'aj                 s                                                  fccacg                       fg',
    'bkz  ABJGsMrsrrHCFsrrMEM Ix K wwwM DoHyyL                        MMnIygccbcf                       bb',
    'bgb  bafbbababababaabbaf ba f abfg babbaf     I   H   I         Hgfggffccbf                        aa',
    'bfccccf                                      Af   fMMfgE  K vrMzacb    gbf                          b',
    'fgffggg                             w    MA  g   fgfgbbaMJaLabbabff                                 a',
    'a             yuyv   wxdMC     xFzAfb  vwbfccgccccgfab  bf g               xF                       g',
    'b        wvEzbbaba Bwbbbba Gw  abab   Aabafggffggffgb         sAAM C       ab     s  BHw q          f',
    'a   M    ababababbbba      ab J  accccbbabccfw          A  D zfgffAaA  zfihb  w  ArvJafb a   zA   rya',
    'brsxf     ab                  f  bffgggfabgfba lvzCB  GJfg a bca  g f  bbhf   bccaaafcg     Aafcccgab',
    'fgbabyv                                       abbbaahiafa f v g         fgf    gf   gbf    Af bccgf b',
    'b   bbaz                                           ggbf     b                              g   gfg  b',
    'b      a   wIpHymv                                                                     yM b         b',
    'a         ybabaaba                                                                     aga          b',
    'f         bahia                                                                  xw E               f',
    'b      w    bb                                                                   bbcfMIHv           b',
    'a      b                                                        K       o          ggffga   D       a',
    'b  z  ba            y b                              Bpz       vfihhiiihg                   a      sf',
    'bAvaihihgIxAMdK  MFDaawHoGvvMeBzzrMAMx    FCDtMy  H  bba IAL  LbaiihhihbfHAvxuEzzyqIDCAGwwKgfMyxeGzba',
    'fgaaabababafggfccfgbababababbfababfggbhiiabababbccgccccccafgccfbabaihababababbababbbbabaaafgfbabababg',
    'b             fggf                    baab     bgfbfggffgabafgbb  abba                              b',
    'b                                                                                                   a',
    'a                                                                                                   b',
    'a                                                                                                   a',
    'a                                                                                                   a',
    'a                                                                                                   b',
    'b                                                                                                   a',
    'abababbabababbabababababababbababababbababababbababababbabababbabababbabababbababababaaaaaababbbbbbaa'
  ],
  [
    'gfggfgfggfgfgabbababbgfggfgfgggffgabababbbababbbabgfggfabgbgabgafffgfgggfgfgfggfgffgfgfggfgffffffgggg',
    'f                                                                                  sr               g',
    'g    zvBqrs A yG          F                                        v  v       Ho  ssr xB         DLsg',
    'f n  abbabf bHbbhiihihihibax                              JB       aw acccccccgfgfggfgabf     MpIffgg',
    'fcccccca     baahihihihhhg b zD   o       EJpw vH  yC  xz gfhiihihiba fgfggfggf    abcg    HtKggf   g',
    'fffabgba        gfhihihbaf   ab  Aacccccccgfga ab  ba  ab   aihihiia               f b   C fff      g',
    'f                fiiiia          ggcccccccfsr                bihiiib   ExyrssGzev lg    Mgg         g',
    'f    rrr          ggffa           gfcccccgfrs      r     s    abagbccccgabbbbbbba gg   Ff           f',
    'f    sss  zuA                       fcccaigff ssr  sz  Asrsrr   ssbcccf            g   fg           a',
    'fccccbbb  aaa                        fcffb    fab  fa  gbfgsss srr gffg            fA               b',
    'ffffghg                               g                    fff sabff                gA              b',
    'g    b                                                         a                     fI   H         g',
    'f                                                                                r    gfM gvBqw     g',
    'f                   MtALD      A  r sI A s wv CtxF                  rr     px    g      g  baabA    g',
    'f                oHIfffgfihhihif  f gg f f ab bfaa                 qbbv A waaC                gfG   f',
    'g              CKfgfg   fhihiig                  gA                bhib f aiha                 fgA  g',
    'g              fgg       gfgff                    fz                bb     aa                   gf  g',
    'b       j   g                                rmr   by                                               f',
    'bowzyBvykHIfgMrs MA KKd E    JEMeIIA   At prsrrsrsHAbwvvAKBMuGAFAHvH ELzGAAJCwByzDMAAAFtIHoKEAAMxCzMa',
    'fababbaaagffgfggfgfgfggffhihigfgfgfgcccggffggffffffffabfgfgfgfggagfghgfgfggfbbbbagfgfggfgfgfggfabbbfg',
    'b                       baabaa     fggfg                            a                               a',
    'b                                                                                                   a',
    'a                                                                                                   b',
    'a                                                                                                   a',
    'a                                                                                                   a',
    'a                                                                                                   b',
    'b                                                                                                   a',
    'abababbabababbabababababababbababababbababababbababababbabababbabababbabababbababababaaaaaababbbbbbaa'
  ],
  [
    'gfggfgfggfgfgabbababbgfggfgfgggffgabababbbababbbabgfggfabgbgabgafffgfgggfgfgfggfgffgfgfggfgffffffgggabfggfgfggfgfgabbababbgfggfgfgggffgabababbbababbbabgfggfabgbgabgafffgfgggfgfgfggfgffgfgfggfgffffffgggg',
    'f                                                                                                                                                                                                       jg',
    'g     rrH Ix                                                  v                                gz                          IuA      A                                               vtx                 kg',
    'f   rdssarba                              z t M HuJ x      w gf                             vC zbsG y v w             BFA  gff    Ezg                                             x aaa                sag',
    'fslrbaaa b gJ                           Lygfgcf bbg a   DzGa  bz                           Fba baab b biaw         KA aaf        Mfa                zxtGvdrr                    A bz                  Bb g',
    'ffbb        frstxE  w B   rryw  GDevH CKfa  gcf a  sr yyffg    axy                        wa           bha       v gf           yf              Cs  ababbaab                  zsg  g                 xg  g',
    'f            abaag  a axFzaaabssbbaag fg    gfg g  rs ab        ba                       Bb             g   vv q f             xgb             Mba                            ab                    rf   g',
    'f            g   f  aibbba    ab bba            f  aag                              y Meoa                 Abb a              wa              rf                           Hv                    Fs f    f',
    'f                    b f                        gs         y                        acfggf                 f                 Cb               f                            gg                 Ar ga      a',
    'f                                               fr ss Cx  za        rpA            aag                 Az I                  b   DKLHeFCqA   fA                         off                   ff       rrb',
    'f                    w zx                       ag gf ba  b         abg          xMbfb     A    Dz tr  fg a                vfa   bfgfgabbb A gf                        Maaa                B           sfb',
    'g                   vaxba                                Aa            Fz        bafg      fihaiggcgg                     Mg s ar   s    rra            vH x Ev   AD  pghb                ra        zn g g',
    'f                  va a   HxEM                          Ag             aa KA    gfgaf GmHE  bbba  f                     M fa r assssr   ssb             gg a bb srff  aiib             A Jg  w Id ssbb   g',
    'f                M b      fggg IeD v Iz  Fo  vz  y  Mv If                 ffxz ggafffhabba                              gfaK oB frgrbzItra                      ab    bbib             qvg   araa ab     g',
    'f               zaggf          fff aifgf gf  aa za rff g                    ab       b                                     f faagf a fgga                              aha             bb     b          f',
    'g              Aab                  g           b  g                                                                                                                    g                                g',
    'g           v  g                      B                             w            yz  My                   A                                            A      Mp                          o              g',
    'b           b    w                    ahhiihhhhhiiiihihihihiiiiiiiihbccccccccccccbaccgfcccccccccccccccccccghhiiiihiihiiihhhhhihhhiiihiiiiihiiiihhhhhhhhfihihhhabccccccccccccccccccccccccccfiihhhhhihiiiiif',
    'byzHxvwAuJvga rssaccccccccccccccccccccgihhhihiiihiiiiihhhihihihhiiibgbcccccccccccccccccccccccccccccccccccbbgfihibhhghhiihiihihhihhhhiiiiiiiiiiiihhiihibgfghihfffcccccccccccccccccccccccccfgfhihihihihiiiha',
    'fababbaaagffgfggfgcccccccccccccccccccggaihiiihhihiihhhiiihhhhhhiiiifgfgccccccccccccccccccccccccccccccccccbbabiihbhibhihhhhihhhhhhihihihihihihhhiibiiihbababhhggggccccccccccccccccccccccccbgahihiihiiiihhhg',
    'b                 fgfggffffgfgfgfgfggggggffggffffffffabfgfgfgfggagfgfgfgfggfbbbbagfgfggfgfgfggfabbbffgababbbabababbabababababababbababababbababababbababababbabababbabababbffggfgfgfgfgfgfgfggfgbabbbbbbaa',
    'b                                                                                                                                                                                                        a',
    'a                                                                                                                                                                                                        b',
    'a                                                                                                                                                                                                        a',
    'a                                                                                                                                                                                                        a',
    'a                                                                                                                                                                                                        b',
    'b                                                                                                                                                                                                        a',
    'abababbabababbabababababababbababababbababababbababababbabababbabababbabababbababababaaaaaababbbbbbababababbabababbabababababababbababababbababababbababababbabababbabababbabababbababababaaaaaababbbbbbaa'
  ]
];