export const options = {
  game: function() {},
  width: window.innerWidth,
  height: window.innerHeight,
  $canvas: document.getElementById('canvas'),
  context: document.getElementById('canvas').getContext('2d'),
  BGIW: 2048,
  BGIH: 1546,
  TIW: 128,
  TIH: 128,
  t: 0,
  images: [],
  tiles: [],
  enemies: [],
  transformToEnemies: [],
  transformToTiles: [],
  imagesCounter: 0,
  $loading: document.getElementById('loading'),
  currentLevelIndex: 0,
  health: 1000,
  imagesQuantity: 0,
  moving: false,
  keys: {},
  gravity: 0.3,
  friction: 0.6,
  crystals: [],
  crystalKeys: {
    g: false,
    y: false,
    b: false
  },
  score: 0,
  info: false
};