export const options = {
  game: null,
  width: window.innerWidth,
  height: window.innerHeight,
  $canvas: null,
  context: null,
  BGIW: 2048,
  BGIH: 1546,
  t: 0,
  images: [],
  tiles: [],
  enemies: [],
  imagesCounter: 0,
  $loading: null,
  currentLevelIndex: 0,
  health: 1000,
  imagesQuantity: 0,
  moving: false,
  keys: {},
  gravity: 0.3,
  friction: 0.6,
  crystals: [],
  crystalKeys: {
    g: false,
    y: false,
    b: false
  },
  score: 0,
  info: false
};